- pipeline: "Build"
  trigger_mode: "ON_EVERY_PUSH"
  ref_name: "master"
  ref_type: "BRANCH"
  trigger_condition: "ALWAYS"
  actions:
  - action: "Execute: gatsby build"
    type: "BUILD"
    working_directory: "/buddy/mattjames-info"
    docker_image_name: "library/node"
    docker_image_tag: "10"
    execute_commands:
    - "yarn"
    - "gatsby build"
    setup_commands:
    - "npm install -g gatsby-cli"
    volume_mappings:
    - "/:/buddy/mattjames-info"
    trigger_condition: "ALWAYS"
    shell: "BASH"
  - action: "Upload files to mattjames.info"
    type: "SFTP"
    input_type: "BUILD_ARTIFACTS"
    local_path: "public/"
    remote_path: "/home/mattjamescarney/mattjames.info/"
    login: "mattjamescarney"
    password: "secure!3V6zkjOy0Wt4EUkCXmFCQA==.g0vvpNJFZ6XisSSIx3jFeA=="
    host: "mattjames.info"
    port: "22"
    authentication_mode: "PASS"
  - action: "Send Email notification"
    type: "EMAIL"
    title: "$BUDDY_PIPELINE_NAME execution #$BUDDY_EXECUTION_ID"
    content: "Website successfully updated."
    recipients: "mattjcarney@gmail.com"
    trigger_condition: "ALWAYS"
  - action: "Send Email notification"
    type: "EMAIL"
    trigger_time: "ON_FAILURE"
    title: "$BUDDY_PIPELINE_NAME execution #$BUDDY_EXECUTION_ID"
    content: "ERROR: Website DID NOT update."
    recipients: "mattjcarney@gmail.com"
    trigger_condition: "ALWAYS"
