on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
name: Build Gatsby Site and Push to Repo
jobs:
  Build-Gatsby-And-Push:
    name: Build Gatsby Site and Push to Repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    
    - name: Commit files
      run: |
        git config --local user.email "hello@mattjames.fino"
        git config --local user.name "Matt James"
        git commit -m "Add build to public" -- public/
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/