# OLD WORKFLOW -- KEEP FOR TESTING PURPOSES
# name: build and deploy build
#
# on:
#  push:
#    branches:    
#      - master
#
# jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build Gatsby Site
#        uses: jzweifel/gatsby-cli-github-action@master
#        with:
#          gatsby-arg: build
#      - name: Upload ftp
#        uses: sebastianpopp/ftp-action@releases/v2
#        with:
#          host: ${{ secrets.FTP_SERVER }}
#          user: ${{ secrets.FTP_USERNAME }}
#          password: ${{ secrets.FTP_PASSWORD }}
#          localDir: "public/"
#          remoteDir: "/mattjames.info"
          
on:
  push:
    branches:
      - master
name: Build and Publish Website
jobs:
  Build-Gatsby-And-Push:
    name: Build Gatsby Site and Push to Repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build
    
    - name: Commit files
      run: |
        git config --local user.email "hello@mattjames.fino"
        git config --local user.name "Matt James"
        git add public/
        git commit -m "Add build to public" -- public/
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
